<template>
  <w-icon v-bind="$attrs">
    <svg viewBox="0 0 384 512"><path d="M0 352a160 160 0 00160 160h64a160 160 0 00160-160V224H0zM176 0h-16A160 160 0 000 160v32h176zm48 0h-16v192h176v-32A160 160 0 00224 0z"/></svg>
  </w-icon>
</template>

<script>
/* This file is auto generated by generateIcon.js */
import WIcon from '../index.js'

export default {
  name: 'Mouse',
  components: {
    WIcon
  },
}
</script>
    