<template>
  <w-icon v-bind="$attrs">
    <svg viewBox="0 0 448 512"><path d="M448 48v32a16 16 0 01-16 16h-48v368a16 16 0 01-16 16h-32a16 16 0 01-16-16V96h-32v368a16 16 0 01-16 16h-32a16 16 0 01-16-16V352h-32a160 160 0 010-320h240a16 16 0 0116 16z"/></svg>
  </w-icon>
</template>

<script>
/* This file is auto generated by generateIcon.js */
import WIcon from '../index.js'

export default {
  name: 'Paragraph',
  components: {
    WIcon
  },
}
</script>
    