<template>
  <w-icon v-bind="$attrs">
    <svg viewBox="0 0 512 512"><path d="M512 512H0V0h512v512z"/></svg>
  </w-icon>
</template>

<script>
/* This file is auto generated by generateIcon.js */
import WIcon from '../index.js'

export default {
  name: 'SquareFull',
  components: {
    WIcon
  },
}
</script>
    