<template>
  <w-icon v-bind="$attrs">
    <svg viewBox="0 0 448 512"><path d="M448 230.17V480H0V230.17h141.13v124.92h165.74V230.17zM306.87 32H141.13v124.91h165.74z"/></svg>
  </w-icon>
</template>

<script>
/* This file is auto generated by generateIcon.js */
import WIcon from '../index.js'

export default {
  name: 'Unsplash',
  components: {
    WIcon
  },
}
</script>
    