<template>
  <w-icon v-bind="$attrs">
    <svg viewBox="0 0 320 512"><path d="M129.5 512V345.9L18.5 48h55.8l81.8 229.7L250.2 0h51.3L180.8 347.8V512h-51.3z"/></svg>
  </w-icon>
</template>

<script>
/* This file is auto generated by generateIcon.js */
import WIcon from '../index.js'

export default {
  name: 'YandexInternational',
  components: {
    WIcon
  },
}
</script>
    